# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTZjZTRmMWJhYzRlMjNhZmRkM2RiZWYyMDJlZTQ4YTkyMDAyYWFmYmE4MzViMWY4YTAyZTZmNDM2ZDVmODAwNmU5OTQxZTBlZTk1Y2I0N2FlZGNiY2ZmYjM2ZTQwMjEyOWE3OWM4ZDYwYTA3MjQ4YzNlYjViMDg0ZDAyYmRmZDU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
